### ISSUE TITLE
Evans Hunt - Jucier update for EV

### ISSUE THREAD

**Issue by ryanjohnston** [ryanjohnston/Journal#128]
Jucier made a change to their json data due to a request from Twitter. The EV social dashboard screen is no longer showing any Twitter data, only Instagram. The page needs to be edited to have Twitter back.

# To Do
- [ ] Business Requirements

# Reference
- [ ] [SquareSpace Development Site]()
- [ ] [SquareSpace Development Server]()

# See Also
- [ ] #32 Business Requirements
- [ ] #69 JavaScript Development on MacOS
- [ ] #96 SquareSpace Resources & Workflow
- [ ] #95 Dockerize SquareSpace Development
- [ ] #33 Development Workflow
- [ ] #37 List of Development Software

**Comment by ryanjohnston** [comment]
Updated EHdevelopment repo with documentation on how to work with EV codebase and SquareSpace.

**Comment by ryanjohnston** [comment]
https://github.com/ryanjohnston/EHDevelopment/pull/1
