### ISSUE TITLE
PHP Knowledge Document

### ISSUE THREAD

**Issue by ryanjohnston** [ryanjohnston/Journal#162]

**Comment by ryanjohnston** [comment]
# Dependency Injection

- [ ] https://matthiasnoback.nl/2018/02/reducing-call-sites-with-dependency-injection-and-context-passing

**Comment by ryanjohnston** [comment]
# Task Running & Build Scripts
- [ ] [Composer Scripts](https://blog.martinhujer.cz/have-you-tried-composer-scripts)
- [ ] [Make Files for Lazy Devs](https://localheinz.com/blog/2018/01/24/makefile-for-lazy-developers)

**Comment by ryanjohnston** [comment]
# Sessions
- [ ] [PHP Sessions in Depth](https://www.phparch.com/2018/01/php-sessions-in-depth)

**Comment by ryanjohnston** [comment]
# Unit Testing
- [ ] [Do Not Write Useless Tests](https://www.brandonsavage.net/dont-write-useless-unit-tests)
